// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5QL1G1TPBYwo32qIfil2h0I6UGsGAX8o',
    appId: '1:1094119666664:web:0312d812612d6131f42a5d',
    messagingSenderId: '1094119666664',
    projectId: 'traxer-ba49d',
    authDomain: 'traxer-ba49d.firebaseapp.com',
    storageBucket: 'traxer-ba49d.firebasestorage.app',
    measurementId: 'G-BSE3QQQ2S2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTp2RlY0JAQBQyC9UasA9PB4B86pGTOCs',
    appId: '1:1094119666664:android:db74e33d97f88b0bf42a5d',
    messagingSenderId: '1094119666664',
    projectId: 'traxer-ba49d',
    storageBucket: 'traxer-ba49d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArGckeRG7xbnhc2mFANzeX3QY9GYc7G8o',
    appId: '1:1094119666664:ios:d001f3eab6b3bf10f42a5d',
    messagingSenderId: '1094119666664',
    projectId: 'traxer-ba49d',
    storageBucket: 'traxer-ba49d.firebasestorage.app',
    iosBundleId: 'com.app.traxer.traxer',
  );
}
